/******* Do not edit this file *******
Simple Custom CSS and JS - by Silkypress.com
Saved: Sep 07 2016 | 21:02:12 */
var urlAJAX = "";

function saveToDB(userArray){
	
	var stringUsers = JSON.stringify(userArray);

  	console.log(stringUsers);

	jQuery.ajax({
		method: "POST",
		url: "http://www.desafioxcfutangue.cl/wp-admin/registerUser.php",
        data: {
          users : stringUsers,
        },
        async: true,
        success: function(data){
          console.log("successo", data);
        },
        error: function(err){
          console.log("errorre", err);
        },
        timeout: function(msg){
          console.log("timeout", msg);
        }
    });

}

function createVoucherFile(){

	var voucher = jQuery(".input-comprobante").val();
}